export const SET_LOCAL_STREAM = 'SET_LOCAL_STREAM';
export const GOT_REMOTE_STREAM = 'GOT_REMOTE_STREAM';
export const ESTABLISH_PEER_CONNECTIONS = 'ESTABLISH_PEER_CONNECTIONS';
export const CONFIGURE_CHANNEL = 'CONFIGURE_CHANNEL';
export const ADD_CLIENT = 'ADD_CLIENT';
export const GOT_REMOTE_DESCRIPTION = 'GOT_REMOTE_DESCRIPTION';
export const GOT_REMOTE_ICE_CANDIDATE = 'GOT_REMOTE_ICE_CANDIDATE';
export const SAVE_PEER_CONNECTION = 'SAVE_PEER_CONNECTION'
